# Generated by Django 5.0.1 on 2024-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_picture_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='picture',
            name='credits',
            field=models.CharField(max_length=100),
        ),
    ]
