# Generated by Django 5.0.1 on 2024-01-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0006_picture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
